name: wiredash_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0 <4.0.0"

dependencies:
  device_frame: ^1.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  google_fonts: ^2.3.2

  wiredash:
    path: ../

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true
