include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - example/**
    - lib/src/common/translation/l10n/**


linter:
  rules:
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false