name: wiredash_theming
description: Wiredash sample project demonstrating theming
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:

  wiredash:
    path: ../../

dev_dependencies:
  lint: '>=1.0.0 <=3.0.0'
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
