name: Pull Requests

on:
  pull_request:
  push:
    branches:
      - stable
      - beta
      - master

jobs:
  # Wiredash is developed on beta, we therefore check code style here
  code_style:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:beta
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env flutter analyze --fatal-infos --fatal-warnings .
      - name: Check formatting
        run: sudo --preserve-env=PATH env dartfmt --dry-run --set-exit-if-changed .

  pr-min:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:2.5.0
    if: github.base_ref == 'stable' || github.ref == 'refs/heads/stable'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web

  pr-stable:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable
    if: github.base_ref == 'stable' || github.ref == 'refs/heads/stable'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web

  pr-beta:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:beta
    if: github.base_ref == 'beta' || github.ref == 'refs/heads/beta'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web

  pr-master:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:master
    if: github.base_ref == 'master' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web
