name: Pull Requests

on:
  pull_request:
  push:
    branches:
      - stable
      - beta
      - dev

jobs:
  pr-stable:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable
    if: github.base_ref == 'stable' || github.ref == 'refs/heads/stable'
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Check formatting
        run: sudo --preserve-env=PATH env dartfmt --dry-run --set-exit-if-changed lib
      - name: Analyze
        run: sudo --preserve-env=PATH env dartanalyzer --fatal-infos --fatal-warnings lib
      - name: Test
        run: sudo --preserve-env=PATH env flutter test --no-sound-null-safety

  pr-beta:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:beta
    if: github.base_ref == 'beta' || github.ref == 'refs/heads/beta'
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Check formatting
        run: sudo --preserve-env=PATH env dartfmt --dry-run --set-exit-if-changed lib
      - name: Analyze
        run: sudo --preserve-env=PATH env flutter analyze --fatal-infos --fatal-warnings lib
      - name: Test
        run: sudo --preserve-env=PATH env flutter test --no-sound-null-safety

  pr-dev:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:dev
    if: github.base_ref == 'dev' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Check formatting
        run: sudo --preserve-env=PATH env dartfmt --dry-run --set-exit-if-changed lib
      - name: Analyze
        run: sudo --preserve-env=PATH env flutter analyze --fatal-infos --fatal-warnings lib
      - name: Test
        run: sudo --preserve-env=PATH env flutter test --no-sound-null-safety

  pr-master:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:master
    if: github.base_ref == 'dev' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Download dependencies
        run: flutter packages get
      - name: Check formatting
        run: dartfmt --dry-run --set-exit-if-changed lib
      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings lib
      - name: Test
        run: flutter test --no-sound-null-safety